export {
  type PrivacyLevel,
  type ItemType,
  type PerturbationResult,
  type MatchResult,
  type BenchmarkResult,
  type EvalReport,
  EPSILON_MAP,
  type PerturbMode,
  EMBEDDING_CONFIG,
  HNSW_DEFAULTS,
  PROTOCOL_DEFAULTS,
} from './types.js';

export {
  dotProduct,
  l2Norm,
  normalize,
  cosineSimilarity,
  cosineSimilaritySafe,
} from './vectors.js';

export {
  sampleLaplace,
  calibrateScale,
  perturbVector,
  perturbWithLevel,
  privacyLevelToEpsilon,
} from './perturbation.js';

export { EmbeddingEngine, rewriteForMatching, type EmbeddingPrefix } from './embedding.js';

export { BOOTSTRAP_RELAYS, DEFAULT_RELAY_PORT } from './bootstrap.js';
export { assertSecureRelayTransportEndpoint } from './relay-transport.js';

export {
  RELAY_DISCOVERY_VERSION,
  RELAY_PEER_REQUEST_FRAME_TYPE,
  RELAY_PEER_RESPONSE_FRAME_TYPE,
  MAX_RELAY_DESCRIPTOR_LIFETIME_MS,
  MAX_RELAY_PEERS_PER_RESPONSE,
  MAX_RELAY_DISCOVERY_FRAME_BYTES,
  type RelayReachability,
  type RelayContactHintSource,
  type RelayCapabilitiesV1,
  type RelayStorageCapacityV1,
  type RelayDescriptorBodyV1,
  type RelayDescriptorV1,
  type CreateRelayDescriptorInputV1,
  type RelayContactHintV1,
  type RelayPeerRequestKeyMaterialV1,
  type RelayPeerRequestBodyV1,
  type RelayPeerRequestV1,
  type RelayPeerResponseBodyV1,
  type RelayPeerResponseV1,
  type RelayPeerRequestFrameV1,
  type RelayPeerResponseFrameV1,
  createRelayDescriptorV1,
  verifyRelayDescriptorV1,
  isRelayDescriptorActiveV1,
  createRelayContactHintV1,
  verifyRelayContactHintV1,
  generateRelayPeerRequestKeyMaterialV1,
  createRelayPeerRequestV1,
  verifyRelayPeerRequestV1,
  isRelayPeerRequestActiveV1,
  createRelayPeerResponseV1,
  verifyRelayPeerResponseV1,
  isRelayPeerResponseActiveV1,
  createRelayPeerRequestFrameV1,
  createRelayPeerResponseFrameV1,
  serializeRelayPeerRequestFrameV1,
  serializeRelayPeerResponseFrameV1,
  parseRelayPeerRequestFrameV1,
  parseRelayPeerResponseFrameV1,
} from './relay-discovery.js';

export {
  RELAY_LINK_VERSION,
  RELAY_LINK_OPEN_FRAME_TYPE,
  RELAY_LINK_ACCEPT_FRAME_TYPE,
  MAX_RELAY_LINK_HANDSHAKE_LIFETIME_MS,
  type RelayLinkOpenBodyV1,
  type RelayLinkOpenV1,
  type RelayLinkAcceptBodyV1,
  type RelayLinkAcceptV1,
  type RelayLinkOpenFrameV1,
  type RelayLinkAcceptFrameV1,
  createRelayLinkOpenV1,
  verifyRelayLinkOpenV1,
  isRelayLinkOpenActiveV1,
  createRelayLinkAcceptV1,
  verifyRelayLinkAcceptV1,
  isRelayLinkAcceptActiveV1,
  createRelayLinkOpenFrameV1,
  createRelayLinkAcceptFrameV1,
  serializeRelayLinkOpenFrameV1,
  serializeRelayLinkAcceptFrameV1,
  parseRelayLinkOpenFrameV1,
  parseRelayLinkAcceptFrameV1,
} from './relay-link.js';

export {
  RELAY_REPLICATION_VERSION,
  RELAY_REPLICA_PUT_FRAME_TYPE,
  RELAY_REPLICA_RECEIPT_FRAME_TYPE,
  RELAY_REPLICA_INVENTORY_REQUEST_FRAME_TYPE,
  RELAY_REPLICA_INVENTORY_RESPONSE_FRAME_TYPE,
  RELAY_REPLICA_INVENTORY_BATCH_REQUEST_FRAME_TYPE,
  RELAY_REPLICA_INVENTORY_BATCH_RESPONSE_FRAME_TYPE,
  RELAY_REPLICA_RECONCILIATION_REQUEST_FRAME_TYPE,
  RELAY_REPLICA_RECONCILIATION_RESPONSE_FRAME_TYPE,
  RELAY_REPLICA_HANDOFF_REQUEST_FRAME_TYPE,
  RELAY_REPLICA_HANDOFF_RESPONSE_FRAME_TYPE,
  MAX_RELAY_REPLICA_REQUEST_LIFETIME_MS,
  MAX_RELAY_REPLICA_INVENTORY_BATCH_RECEIPTS,
  MAX_RELAY_REPLICA_HANDOFF_OPERATIONS,
  type RelayReplicaReceiptStatusV1,
  type RelayReplicaInventoryStatusV1,
  type RelayReplicaInventoryBatchStatusV1,
  type RelayReplicaReconciliationStatusV1,
  type RelayReplicaRejectionReasonV1,
  type RelayReplicaInventoryRejectionReasonV1,
  type RelayReplicaReconciliationRejectionReasonV1,
  type RelayReplicaPutBodyV1,
  type RelayReplicaPutV1,
  type RelayReplicaReceiptBodyV1,
  type RelayReplicaReceiptV1,
  type RelayReplicaInventoryRequestBodyV1,
  type RelayReplicaInventoryRequestV1,
  type RelayReplicaInventoryResponseBodyV1,
  type RelayReplicaInventoryResponseV1,
  type RelayReplicaInventoryBatchRequestBodyV1,
  type RelayReplicaInventoryBatchRequestV1,
  type RelayReplicaInventoryBatchResponseBodyV1,
  type RelayReplicaInventoryBatchResponseV1,
  type RelayReplicaReconciliationRequestBodyV1,
  type RelayReplicaReconciliationRequestV1,
  type RelayReplicaReconciliationResponseBodyV1,
  type RelayReplicaReconciliationResponseV1,
  type RelayReplicaOperationReferenceV1,
  type RelayReplicaHandoffRequestBodyV1,
  type RelayReplicaHandoffRequestV1,
  type RelayReplicaHandoffResponseBodyV1,
  type RelayReplicaHandoffResponseV1,
  type RelayReplicaPutFrameV1,
  type RelayReplicaReceiptFrameV1,
  type RelayReplicaInventoryRequestFrameV1,
  type RelayReplicaInventoryResponseFrameV1,
  type RelayReplicaInventoryBatchRequestFrameV1,
  type RelayReplicaInventoryBatchResponseFrameV1,
  type RelayReplicaReconciliationRequestFrameV1,
  type RelayReplicaReconciliationResponseFrameV1,
  type RelayReplicaHandoffRequestFrameV1,
  type RelayReplicaHandoffResponseFrameV1,
  createRelayReplicaPutV1,
  verifyRelayReplicaPutV1,
  isRelayReplicaPutActiveV1,
  createRelayReplicaReceiptV1,
  verifyRelayReplicaReceiptV1,
  isDurabilityReceiptV1,
  isRelayReplicaReconciliationReceiptV1,
  createRelayReplicaInventoryRequestV1,
  verifyRelayReplicaInventoryRequestV1,
  isRelayReplicaInventoryRequestActiveV1,
  createRelayReplicaInventoryResponseV1,
  verifyRelayReplicaInventoryResponseV1,
  createRelayReplicaInventoryBatchRequestV1,
  verifyRelayReplicaInventoryBatchRequestV1,
  isRelayReplicaInventoryBatchRequestActiveV1,
  createRelayReplicaInventoryBatchResponseV1,
  verifyRelayReplicaInventoryBatchResponseV1,
  decodeRelayReplicaInventoryBatchPresenceV1,
  createRelayReplicaReconciliationRequestV1,
  verifyRelayReplicaReconciliationRequestV1,
  isRelayReplicaReconciliationRequestActiveV1,
  createRelayReplicaReconciliationResponseV1,
  verifyRelayReplicaReconciliationResponseV1,
  createRelayReplicaHandoffRequestV1,
  verifyRelayReplicaHandoffRequestV1,
  isRelayReplicaHandoffRequestActiveV1,
  createRelayReplicaHandoffResponseV1,
  verifyRelayReplicaHandoffResponseV1,
  decodeRelayReplicaHandoffResultV1,
  createRelayReplicaPutFrameV1,
  createRelayReplicaReceiptFrameV1,
  createRelayReplicaInventoryRequestFrameV1,
  createRelayReplicaInventoryResponseFrameV1,
  createRelayReplicaInventoryBatchRequestFrameV1,
  createRelayReplicaInventoryBatchResponseFrameV1,
  createRelayReplicaReconciliationRequestFrameV1,
  createRelayReplicaReconciliationResponseFrameV1,
  createRelayReplicaHandoffRequestFrameV1,
  createRelayReplicaHandoffResponseFrameV1,
  serializeRelayReplicaPutFrameV1,
  serializeRelayReplicaReceiptFrameV1,
  serializeRelayReplicaInventoryRequestFrameV1,
  serializeRelayReplicaInventoryResponseFrameV1,
  serializeRelayReplicaInventoryBatchRequestFrameV1,
  serializeRelayReplicaInventoryBatchResponseFrameV1,
  serializeRelayReplicaReconciliationRequestFrameV1,
  serializeRelayReplicaReconciliationResponseFrameV1,
  serializeRelayReplicaHandoffRequestFrameV1,
  serializeRelayReplicaHandoffResponseFrameV1,
  parseRelayReplicaPutFrameV1,
  parseRelayReplicaReceiptFrameV1,
  parseRelayReplicaInventoryRequestFrameV1,
  parseRelayReplicaInventoryResponseFrameV1,
  parseRelayReplicaInventoryBatchRequestFrameV1,
  parseRelayReplicaInventoryBatchResponseFrameV1,
  parseRelayReplicaReconciliationRequestFrameV1,
  parseRelayReplicaReconciliationResponseFrameV1,
  parseRelayReplicaHandoffRequestFrameV1,
  parseRelayReplicaHandoffResponseFrameV1,
} from './relay-replication.js';

export {
  generateProjectionMatrix,
  hashEmbedding,
  hammingDistance,
  hammingSimilarity,
  expectedHammingSimilarity,
  getSharedProjectionMatrix,
  LSH_DEFAULTS,
} from './lsh.js';

export {
  type Identity,
  type SigningKeyPair,
  type KeyPair,
  type BoxResult,
  type SecretBoxResult,
  generateIdentity,
  generateSigningKeyPair,
  publicKeyToDid,
  didToPublicKey,
  sign,
  verify,
  sha512,
  boxEncrypt,
  boxDecrypt,
  generateEphemeralKeyPair,
  deriveSharedSecret,
  secretboxEncrypt,
  secretboxDecrypt,
  exportIdentity,
  importIdentity,
  encodeBase64,
  decodeBase64,
  encodeUTF8,
  decodeUTF8,
} from './crypto.js';

export {
  MATCH_NOTICE_MESSAGE_TYPE,
  MAILBOX_REQUEST_FRAME_TYPE,
  MAILBOX_DEPOSIT_FRAME_TYPE,
  MAILBOX_RESPONSE_MESSAGE_TYPE,
  type MatchNoticePayload,
  type MailboxPayloadType,
  type PublicationMailboxRecipient,
  type EncryptedMailboxEnvelope,
  type MailboxRequestBody,
  type MailboxRequest,
  type MailboxRequestFrame,
  type MailboxDepositBody,
  type MailboxDepositRequest,
  type MailboxDepositFrame,
  type MailboxResponsePayload,
  createMailboxEnvelopeId,
  createMatchNoticeMessage,
  verifyMatchNoticeMessage,
  encryptMatchNotice,
  verifyMailboxEnvelope,
  decryptMatchNotice,
  encryptRelationshipMessage,
  decryptRelationshipMessage,
  createMailboxRequest,
  verifyMailboxRequest,
  createMailboxRequestFrame,
  parseMailboxRequestFrame,
  serializeMailboxRequestFrame,
  createMailboxDepositRequest,
  verifyMailboxDepositRequest,
  createMailboxDepositFrame,
  parseMailboxDepositFrame,
  serializeMailboxDepositFrame,
} from './mailbox-v2.js';

export {
  type RelationshipKeyMaterial,
  type RelationshipMailboxV2,
  type PublicationReferenceV2,
  type ConsentOfferBodyV2,
  type ConsentOfferV2,
  type ConsentAcceptBodyV2,
  type ConsentAcceptV2,
  type RelationshipMessageV2,
  generateRelationshipKeyMaterial,
  createConsentOfferV2,
  createConsentAcceptV2,
  verifyConsentOfferV2,
  verifyConsentAcceptV2,
  verifyRelationshipMessageV2,
  createPairwiseChannelId,
} from './relationship-v2.js';

export {
  RELATIONSHIP_MAILBOX_REQUEST_FRAME_TYPE,
  RELATIONSHIP_MAILBOX_DEPOSIT_FRAME_TYPE,
  type ChannelContentV2,
  type ChannelMessageOperationV2,
  type ChannelCloseOperationV2,
  type ChannelOperationV2,
  type RelationshipMailboxRequestBodyV2,
  type RelationshipMailboxRequestV2,
  type RelationshipMailboxRequestFrameV2,
  type RelationshipMailboxDepositBodyV2,
  type RelationshipMailboxDepositV2,
  type RelationshipMailboxDepositFrameV2,
  createChannelMessageOperationV2,
  createChannelCloseOperationV2,
  verifyChannelOperationV2,
  decryptChannelContentV2,
  encryptChannelOperationV2,
  decryptChannelOperationV2,
  createRelationshipMailboxRequestV2,
  verifyRelationshipMailboxRequestV2,
  createRelationshipMailboxDepositV2,
  verifyRelationshipMailboxDepositV2,
  createRelationshipMailboxRequestFrameV2,
  createRelationshipMailboxDepositFrameV2,
  serializeRelationshipMailboxRequestFrameV2,
  serializeRelationshipMailboxDepositFrameV2,
  parseRelationshipMailboxRequestFrameV2,
  parseRelationshipMailboxDepositFrameV2,
} from './channel-v2.js';

export {
  PROTOCOL_V2_VERSION,
  PUBLICATION_OPERATION_FRAME_TYPE,
  type PublicationKeyMaterial,
  type PublicationMailbox,
  type PublicationFingerprint,
  type PublicationRecord,
  type PublicationRecordBody,
  type PublicationTombstone,
  type PublicationTombstoneBody,
  type PublicationTombstoneReason,
  type PublicationOperation,
  type PublicationOperationFrame,
  type CreatePublicationRecordInput,
  generatePublicationKeyMaterial,
  createPublicationRecord,
  verifyPublicationRecord,
  createPublicationTombstone,
  verifyPublicationTombstone,
  verifyPublicationOperation,
  createPublicationOperationFrame,
  parsePublicationOperationFrame,
  serializePublicationOperationFrame,
  parsePublicationOperation,
  isPublicationActive,
} from './protocol-v2.js';

export {
  ADMISSION_CAPABILITY_KIND_V2,
  type AdmissionCapabilityV2,
  type RelayAdmissionActionV2,
  verifyAdmissionCapabilityV2,
  createAdmissionRequestBindingV2,
  isRelayAdmissionActionV2,
} from './admission-v2.js';

export {
  type MatchPublicationReferenceV2,
  type MatchOperationFingerprintV2,
  type MatchOperationBodyV2,
  type MatchOperationV2,
  type CreateMatchOperationOptionsV2,
  createDeterministicMatchId,
  createMatchOperationV2,
  verifyMatchOperationV2,
  verifyMatchOperationAgainstPublicationsV2,
} from './match-v2.js';

export {
  SEARCH_REQUEST_FRAME_TYPE,
  SEARCH_RESPONSE_MESSAGE_TYPE,
  type SearchKeyMaterialV2,
  type SearchRequestBodyV2,
  type SearchRequestV2,
  type SearchRequestFrameV2,
  type SearchResultV2,
  type SearchResponsePayloadV2,
  type CreateSearchRequestInputV2,
  generateSearchKeyMaterialV2,
  createSearchRequestV2,
  verifySearchRequestV2,
  createSearchRequestFrameV2,
  parseSearchRequestFrameV2,
  serializeSearchRequestFrameV2,
  createSearchResponsePayloadV2,
  verifySearchResponsePayloadV2,
  isSearchRequestActiveV2,
} from './search-v2.js';

export {
  RELAY_QUERY_VERSION,
  RELAY_QUERY_REQUEST_FRAME_TYPE,
  RELAY_QUERY_RESPONSE_FRAME_TYPE,
  MAX_RELAY_QUERY_HOPS,
  MAX_RELAY_QUERY_LIFETIME_MS,
  type RelayQueryRequestV1,
  type RelayQueryResponseV1,
  type RelayQueryStatusV1,
  type RelayQueryRequestFrameV1,
  type RelayQueryResponseFrameV1,
  createRelayQueryRequestV1,
  verifyRelayQueryRequestV1,
  isRelayQueryRequestActiveV1,
  createRelayQueryResponseV1,
  verifyRelayQueryResponseV1,
  createRelayQueryRequestFrameV1,
  createRelayQueryResponseFrameV1,
  serializeRelayQueryRequestFrameV1,
  serializeRelayQueryResponseFrameV1,
  parseRelayQueryRequestFrameV1,
  parseRelayQueryResponseFrameV1,
} from './relay-query.js';

export {
  RELAY_MAILBOX_SYNC_REQUEST_FRAME_TYPE,
  RELAY_MAILBOX_SYNC_RESPONSE_FRAME_TYPE,
  MAX_RELAY_MAILBOX_SYNC_EVENTS,
  type RelayMailboxEventV1,
  type RelayMailboxSyncRequestV1,
  type RelayMailboxSyncResponseV1,
  verifyRelayMailboxEventV1,
  createRelayMailboxSyncRequestV1,
  verifyRelayMailboxSyncRequestV1,
  createRelayMailboxSyncResponseV1,
  verifyRelayMailboxSyncResponseV1,
  serializeRelayMailboxSyncRequestFrameV1,
  serializeRelayMailboxSyncResponseFrameV1,
  parseRelayMailboxSyncRequestFrameV1,
  parseRelayMailboxSyncResponseFrameV1,
  RELAY_RELATIONSHIP_MAILBOX_SYNC_REQUEST_FRAME_TYPE,
  RELAY_RELATIONSHIP_MAILBOX_SYNC_RESPONSE_FRAME_TYPE,
  type RelayRelationshipMailboxEventV1,
  type RelayRelationshipMailboxSyncRequestV1,
  type RelayRelationshipMailboxSyncResponseV1,
  verifyRelayRelationshipMailboxEventV1,
  createRelayRelationshipMailboxSyncRequestV1,
  verifyRelayRelationshipMailboxSyncRequestV1,
  createRelayRelationshipMailboxSyncResponseV1,
  verifyRelayRelationshipMailboxSyncResponseV1,
  serializeRelayRelationshipMailboxSyncRequestFrameV1,
  serializeRelayRelationshipMailboxSyncResponseFrameV1,
  parseRelayRelationshipMailboxSyncRequestFrameV1,
  parseRelayRelationshipMailboxSyncResponseFrameV1,
} from './relay-mailbox-sync.js';

export {
  type Message,
  type PublishPayload,
  type SearchPayload,
  type ConsentPayload,
  type WithdrawPayload,
  type MatchPayload,
  type SearchResultsPayload,
  type ConsentForwardPayload,
  type AckPayload,
  type ConfirmEmbeddingPayload,
  type ConfirmResultPayload,
  type DisclosurePayload,
  type AcceptPayload,
  type RejectPayload,
  type ClosePayload,
  type AuthPayload,
  type ChannelMessagePayload,
  type ChannelForwardPayload,
  MessageTypes,
  createMessage,
  verifyMessage,
  parseMessage,
  serializeMessage,
} from './protocol.js';
