export {
  type PrivacyLevel,
  type ItemType,
  type PerturbationResult,
  type MatchResult,
  type BenchmarkResult,
  type EvalReport,
  EPSILON_MAP,
  type PerturbMode,
  EMBEDDING_CONFIG,
  HNSW_DEFAULTS,
  PROTOCOL_DEFAULTS,
} from './types.js';

export {
  dotProduct,
  l2Norm,
  normalize,
  cosineSimilarity,
  cosineSimilaritySafe,
} from './vectors.js';

export {
  sampleLaplace,
  calibrateScale,
  perturbVector,
  perturbWithLevel,
  privacyLevelToEpsilon,
} from './perturbation.js';

export { EmbeddingEngine, rewriteForMatching, type EmbeddingPrefix } from './embedding.js';

export { BOOTSTRAP_RELAYS, DEFAULT_RELAY_PORT } from './bootstrap.js';

export {
  generateProjectionMatrix,
  hashEmbedding,
  hammingDistance,
  hammingSimilarity,
  expectedHammingSimilarity,
  getSharedProjectionMatrix,
  LSH_DEFAULTS,
} from './lsh.js';

export {
  type Identity,
  type SigningKeyPair,
  type KeyPair,
  type BoxResult,
  type SecretBoxResult,
  generateIdentity,
  generateSigningKeyPair,
  publicKeyToDid,
  didToPublicKey,
  sign,
  verify,
  sha512,
  boxEncrypt,
  boxDecrypt,
  generateEphemeralKeyPair,
  deriveSharedSecret,
  secretboxEncrypt,
  secretboxDecrypt,
  exportIdentity,
  importIdentity,
  encodeBase64,
  decodeBase64,
  encodeUTF8,
  decodeUTF8,
} from './crypto.js';

export {
  MATCH_NOTICE_MESSAGE_TYPE,
  MAILBOX_REQUEST_FRAME_TYPE,
  MAILBOX_DEPOSIT_FRAME_TYPE,
  MAILBOX_RESPONSE_MESSAGE_TYPE,
  type MatchNoticePayload,
  type MailboxPayloadType,
  type PublicationMailboxRecipient,
  type EncryptedMailboxEnvelope,
  type MailboxRequestBody,
  type MailboxRequest,
  type MailboxRequestFrame,
  type MailboxDepositBody,
  type MailboxDepositRequest,
  type MailboxDepositFrame,
  type MailboxResponsePayload,
  createMailboxEnvelopeId,
  createMatchNoticeMessage,
  verifyMatchNoticeMessage,
  encryptMatchNotice,
  verifyMailboxEnvelope,
  decryptMatchNotice,
  encryptRelationshipMessage,
  decryptRelationshipMessage,
  createMailboxRequest,
  verifyMailboxRequest,
  createMailboxRequestFrame,
  parseMailboxRequestFrame,
  serializeMailboxRequestFrame,
  createMailboxDepositRequest,
  verifyMailboxDepositRequest,
  createMailboxDepositFrame,
  parseMailboxDepositFrame,
  serializeMailboxDepositFrame,
} from './mailbox-v2.js';

export {
  type RelationshipKeyMaterial,
  type RelationshipMailboxV2,
  type PublicationReferenceV2,
  type ConsentOfferBodyV2,
  type ConsentOfferV2,
  type ConsentAcceptBodyV2,
  type ConsentAcceptV2,
  type RelationshipMessageV2,
  generateRelationshipKeyMaterial,
  createConsentOfferV2,
  createConsentAcceptV2,
  verifyConsentOfferV2,
  verifyConsentAcceptV2,
  verifyRelationshipMessageV2,
  createPairwiseChannelId,
} from './relationship-v2.js';

export {
  RELATIONSHIP_MAILBOX_REQUEST_FRAME_TYPE,
  RELATIONSHIP_MAILBOX_DEPOSIT_FRAME_TYPE,
  type ChannelContentV2,
  type ChannelMessageOperationV2,
  type ChannelCloseOperationV2,
  type ChannelOperationV2,
  type RelationshipMailboxRequestBodyV2,
  type RelationshipMailboxRequestV2,
  type RelationshipMailboxRequestFrameV2,
  type RelationshipMailboxDepositBodyV2,
  type RelationshipMailboxDepositV2,
  type RelationshipMailboxDepositFrameV2,
  createChannelMessageOperationV2,
  createChannelCloseOperationV2,
  verifyChannelOperationV2,
  decryptChannelContentV2,
  encryptChannelOperationV2,
  decryptChannelOperationV2,
  createRelationshipMailboxRequestV2,
  verifyRelationshipMailboxRequestV2,
  createRelationshipMailboxDepositV2,
  verifyRelationshipMailboxDepositV2,
  createRelationshipMailboxRequestFrameV2,
  createRelationshipMailboxDepositFrameV2,
  serializeRelationshipMailboxRequestFrameV2,
  serializeRelationshipMailboxDepositFrameV2,
  parseRelationshipMailboxRequestFrameV2,
  parseRelationshipMailboxDepositFrameV2,
} from './channel-v2.js';

export {
  PROTOCOL_V2_VERSION,
  PUBLICATION_OPERATION_FRAME_TYPE,
  type PublicationKeyMaterial,
  type PublicationMailbox,
  type PublicationFingerprint,
  type PublicationRecord,
  type PublicationRecordBody,
  type PublicationTombstone,
  type PublicationTombstoneBody,
  type PublicationTombstoneReason,
  type PublicationOperation,
  type PublicationOperationFrame,
  type CreatePublicationRecordInput,
  generatePublicationKeyMaterial,
  createPublicationRecord,
  verifyPublicationRecord,
  createPublicationTombstone,
  verifyPublicationTombstone,
  verifyPublicationOperation,
  createPublicationOperationFrame,
  parsePublicationOperationFrame,
  serializePublicationOperationFrame,
  parsePublicationOperation,
  isPublicationActive,
} from './protocol-v2.js';

export {
  ADMISSION_CAPABILITY_KIND_V2,
  type AdmissionCapabilityV2,
  type RelayAdmissionActionV2,
  verifyAdmissionCapabilityV2,
  createAdmissionRequestBindingV2,
  isRelayAdmissionActionV2,
} from './admission-v2.js';

export {
  type MatchPublicationReferenceV2,
  type MatchOperationFingerprintV2,
  type MatchOperationBodyV2,
  type MatchOperationV2,
  type CreateMatchOperationOptionsV2,
  createDeterministicMatchId,
  createMatchOperationV2,
  verifyMatchOperationV2,
  verifyMatchOperationAgainstPublicationsV2,
} from './match-v2.js';

export {
  SEARCH_REQUEST_FRAME_TYPE,
  SEARCH_RESPONSE_MESSAGE_TYPE,
  type SearchKeyMaterialV2,
  type SearchRequestBodyV2,
  type SearchRequestV2,
  type SearchRequestFrameV2,
  type SearchResultV2,
  type SearchResponsePayloadV2,
  type CreateSearchRequestInputV2,
  generateSearchKeyMaterialV2,
  createSearchRequestV2,
  verifySearchRequestV2,
  createSearchRequestFrameV2,
  parseSearchRequestFrameV2,
  serializeSearchRequestFrameV2,
  createSearchResponsePayloadV2,
  verifySearchResponsePayloadV2,
  isSearchRequestActiveV2,
} from './search-v2.js';

export {
  type Message,
  type PublishPayload,
  type SearchPayload,
  type ConsentPayload,
  type WithdrawPayload,
  type MatchPayload,
  type SearchResultsPayload,
  type ConsentForwardPayload,
  type AckPayload,
  type ConfirmEmbeddingPayload,
  type ConfirmResultPayload,
  type DisclosurePayload,
  type AcceptPayload,
  type RejectPayload,
  type ClosePayload,
  type AuthPayload,
  type ChannelMessagePayload,
  type ChannelForwardPayload,
  MessageTypes,
  createMessage,
  verifyMessage,
  parseMessage,
  serializeMessage,
} from './protocol.js';
