/** Outbound relay discovery over a short, unlinkable WebSocket exchange. */

import WebSocket, { type RawData } from 'ws';
import type { Socket } from 'node:net';
import {
  MAX_RELAY_DISCOVERY_FRAME_BYTES,
  MAX_RELAY_PEERS_PER_RESPONSE,
  createRelayPeerRequestFrameV1,
  createRelayPeerRequestV1,
  isRelayPeerResponseActiveV1,
  parseRelayPeerResponseFrameV1,
  serializeRelayPeerRequestFrameV1,
  verifyRelayContactHintV1,
  type RelayContactHintV1,
  type RelayDescriptorV1,
  type RelayPeerResponseV1,
} from '@resonance/core';

export interface RelayContactDiscoveryOptions {
  supportedGroups?: string[];
  maxPeers?: number;
  timeoutMs?: number;
  now?: () => number;
  onTransportSocket?: (socket: Socket) => void;
}

export interface RelayContactDiscoveryResult {
  hint: RelayContactHintV1;
  responder: RelayDescriptorV1;
  descriptors: RelayDescriptorV1[];
  response: RelayPeerResponseV1;
}

/**
 * Contact one hint and require the endpoint to prove a signed relay identity.
 * The request key is freshly generated by the core protocol for every call.
 */
export function discoverRelayContactV1(
  hint: RelayContactHintV1,
  options: RelayContactDiscoveryOptions = {},
): Promise<RelayContactDiscoveryResult> {
  if (!verifyRelayContactHintV1(hint)) {
    return Promise.reject(new Error('Invalid relay contact hint'));
  }
  const timeoutMs = options.timeoutMs ?? 5_000;
  if (!Number.isSafeInteger(timeoutMs) || timeoutMs < 100 || timeoutMs > 30_000) {
    return Promise.reject(new Error('Relay discovery timeout must be between 100 and 30000 ms'));
  }
  const maxPeers = options.maxPeers ?? MAX_RELAY_PEERS_PER_RESPONSE;
  if (!Number.isSafeInteger(maxPeers) || maxPeers < 1 || maxPeers > MAX_RELAY_PEERS_PER_RESPONSE) {
    return Promise.reject(new Error('Invalid relay discovery peer limit'));
  }
  const clock = options.now ?? Date.now;
  const createdAt = clock();
  const request = createRelayPeerRequestV1({
    supportedGroups: options.supportedGroups ?? [],
    maxPeers,
    createdAt,
    expiresAt: createdAt + Math.min(30_000, timeoutMs + 5_000),
  });
  const serializedRequest = serializeRelayPeerRequestFrameV1(
    createRelayPeerRequestFrameV1(request),
  );

  return new Promise((resolve, reject) => {
    let settled = false;
    let socket: WebSocket;

    const finish = (error?: Error, result?: RelayContactDiscoveryResult): void => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (socket.readyState === WebSocket.OPEN) socket.close(1000, 'discovery_complete');
      else if (socket.readyState === WebSocket.CONNECTING) socket.terminate();
      if (error) reject(error);
      else resolve(result!);
    };

    const timer = setTimeout(() => {
      finish(new Error('Relay discovery timed out'));
    }, timeoutMs);

    try {
      socket = new WebSocket(hint.endpoint, {
        handshakeTimeout: timeoutMs,
        maxPayload: MAX_RELAY_DISCOVERY_FRAME_BYTES,
      });
    } catch (error) {
      clearTimeout(timer);
      reject(asError(error, 'Cannot open relay discovery connection'));
      return;
    }

    socket.on('upgrade', response => options.onTransportSocket?.(response.socket));
    socket.on('open', () => socket.send(serializedRequest));
    socket.on('message', (data: RawData, isBinary: boolean) => {
      if (isBinary) {
        finish(new Error('Relay discovery response must be UTF-8 JSON'));
        return;
      }
      try {
        const frame = parseRelayPeerResponseFrameV1(rawDataToString(data));
        const receivedAt = clock();
        if (!isRelayPeerResponseActiveV1(frame.response, request, receivedAt)) {
          throw new Error('Relay discovery response is invalid or inactive');
        }
        if (hint.expectedRelayId && frame.response.responderId !== hint.expectedRelayId) {
          throw new Error('Relay discovery responder does not match the pinned relay identity');
        }
        const responder = frame.response.descriptors.find(
          descriptor => descriptor.relayId === frame.response.responderId,
        );
        if (!responder) {
          throw new Error('Relay discovery response omits the responder descriptor');
        }
        if (responder.reachability !== 'direct' || !responder.endpoints.includes(hint.endpoint)) {
          throw new Error('Relay responder descriptor does not bind the contacted endpoint');
        }
        finish(undefined, {
          hint: { ...hint },
          responder,
          descriptors: frame.response.descriptors,
          response: frame.response,
        });
      } catch (error) {
        finish(asError(error, 'Invalid relay discovery response'));
      }
    });
    socket.on('error', error => finish(asError(error, 'Relay discovery connection failed')));
    socket.on('close', () => finish(new Error('Relay discovery connection closed without a response')));
  });
}

function rawDataToString(data: RawData): string {
  if (Array.isArray(data)) return Buffer.concat(data).toString('utf8');
  if (data instanceof ArrayBuffer) return Buffer.from(data).toString('utf8');
  return data.toString('utf8');
}

function asError(value: unknown, fallback: string): Error {
  return value instanceof Error ? value : new Error(fallback, { cause: value });
}
